// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0oOjVaAF1sHHDhyCMtRJxG8dJQ9vzWpY',
    appId: '1:2449386254:web:3d1e4c78e6977c609d855f',
    messagingSenderId: '2449386254',
    projectId: 'batik-app-d1c77',
    authDomain: 'batik-app-d1c77.firebaseapp.com',
    storageBucket: 'batik-app-d1c77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcuKe6XW43Lj8PoiqVY3KTv6ft4VWSrXE',
    appId: '1:2449386254:android:b5cfa863ceba45219d855f',
    messagingSenderId: '2449386254',
    projectId: 'batik-app-d1c77',
    storageBucket: 'batik-app-d1c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnDIvkHnry00AQ8aoHEude3hvSE-63RTM',
    appId: '1:2449386254:ios:0858cda44a1ec5739d855f',
    messagingSenderId: '2449386254',
    projectId: 'batik-app-d1c77',
    storageBucket: 'batik-app-d1c77.firebasestorage.app',
    iosBundleId: 'com.example.batikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnDIvkHnry00AQ8aoHEude3hvSE-63RTM',
    appId: '1:2449386254:ios:0858cda44a1ec5739d855f',
    messagingSenderId: '2449386254',
    projectId: 'batik-app-d1c77',
    storageBucket: 'batik-app-d1c77.firebasestorage.app',
    iosBundleId: 'com.example.batikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0oOjVaAF1sHHDhyCMtRJxG8dJQ9vzWpY',
    appId: '1:2449386254:web:f2848a4e375c57809d855f',
    messagingSenderId: '2449386254',
    projectId: 'batik-app-d1c77',
    authDomain: 'batik-app-d1c77.firebaseapp.com',
    storageBucket: 'batik-app-d1c77.firebasestorage.app',
  );
}
